# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.cache/wt [current_project]
set_property parent.project_path C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_verilog -library xil_defaultlib {
  C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/sources_1/imports/CalcDesign10/hex2seg.v
  C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/sources_1/imports/CalcDesign10/keypad-black-box.v
  C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/Display.v
  C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/sources_1/imports/CalcDesign10/clockReset.v
  C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/sources_1/imports/new/CalcaLogic.v
  C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/sources_1/imports/CalcDesign10/CalculatorTop.v
}
read_edif C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/sources_1/imports/CalcDesign10/keypad.ngc
read_xdc C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/constrs_1/imports/CalcDesign10/project_1/Nexys4_Master.xdc
set_property used_in_implementation false [get_files C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/constrs_1/imports/CalcDesign10/project_1/Nexys4_Master.xdc]

read_xdc C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/constrs_1/imports/CalcDesign10/Nexys4_KeypadLeft.xdc
set_property used_in_implementation false [get_files C:/Users/lab/Documents/DigitalSystems/Thursday/CalcDesign10/project_1/project_1.srcs/constrs_1/imports/CalcDesign10/Nexys4_KeypadLeft.xdc]

synth_design -top calculator_top -part xc7a100tcsg324-1
write_checkpoint -noxdef calculator_top.dcp
catch { report_utilization -file calculator_top_utilization_synth.rpt -pb calculator_top_utilization_synth.pb }
